### ISSUE TITLE
Deezloader Crashes on Downloading URL & Playlist

### ISSUE THREAD

**Issue by xyBuskin** [ExtendLord/DeezLoader-Reborn#17]
Hey Guys,

I'm having the following issue: Deezloader 3.0.1 crashes whenever I attempt to download from a URL or Playlist. Sometimes it will download a couple of songs sometimes none sometimes most, but always crashes at some point. I've also tested downloading from charts - works fine, Album - works fine.

OS: Mac OSX 10.13.2
VPN: Currently Brazil but have also tried Canada,Australia,NZ,UK
URL Tested: http://www.deezer.com/us/playlist/4035485582
Playlist Tested: Ultimate Breaks & Beats (approx 400 files)

**Comment by ExtendLord** [comment]
@xyBuskin Can you please go to the terminal and run deezloader from there?
And show me the logs after it crashes.

**Comment by canout** [comment]
Hi guys,
Here is the error :
`Trace: TypeError: Cannot read property '1' of null
    at Deezer.<anonymous> (C:\Users\azerty\AppData\Local\Programs\DeezLoader\resources\app\deezer-api.js:170:31)
    at Request.self.callback (C:\Users\azerty\AppData\Local\Programs\DeezLoader\resources\app\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (C:\Users\azerty\AppData\Local\Programs\DeezLoader\resources\app\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (C:\Users\azerty\AppData\Local\Programs\DeezLoader\resources\app\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at process.<anonymous> (C:\Users\azerty\AppData\Local\Programs\DeezLoader\resources\app\app.js:1126:13)
    at emitOne (events.js:101:20)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)`

You can find the full terminal log attached to this message.
[log.txt](https://github.com/ExtendLord/DeezLoader-Reborn/files/1631047/log.txt)

**Comment by ExtendLord** [comment]
@canout what is the name of the track, album or playlist?

**Comment by ExtendLord** [comment]
@canout You can get the current dev version by compiling it and try to see if it got fixed

**Comment by canout** [comment]
@ExtendLord I have used the playlist provided by @xyBuskin ( http://www.deezer.com/us/playlist/4035485582 )
I'll try with dev version asap.

**Comment by canout** [comment]
@ExtendLord 
On Windows 10 I have an error when entering "npm start dist". I will investigate later.
On Linux the app doesn't crash while downloading the previoulsy mentionned playlist. We can see the following error but no crash.
`
Downloading file to /home/azerty/tmp/deezloader/Synthwave_ a playlist by gbroad84 on Spotify/1 - Mitch Murder - Breeze.mp3
Downloaded: Mitch Murder - Breeze
Downloading file to /home/azerty/tmp/deezloader/Synthwave_ a playlist by gbroad84 on Spotify/1 - Kalax - Time Lapse.mp3
Downloaded: Kalax - Time Lapse
Downloading file to /home/azerty/tmp/deezloader/Synthwave_ a playlist by gbroad84 on Spotify/14 - Timecop1983 - After Life (Outro).mp3
Downloaded: Timecop1983 - After Life (Outro)
error: error Error: Unable to get Track
    at Deezer.<anonymous> (/home/azerty/tmp/deezloader/DeezLoader-Reborn/dist/linux-unpacked/resources/app/deezer-api.js:175:19)
    at Request.self.callback (/home/azerty/tmp/deezloader/DeezLoader-Reborn/dist/linux-unpacked/resources/app/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/home/azerty/tmp/deezloader/DeezLoader-Reborn/dist/linux-unpacked/resources/app/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/home/azerty/tmp/deezloader/DeezLoader-Reborn/dist/linux-unpacked/resources/app/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
Downloading file to /home/azerty/tmp/deezloader/Synthwave_ a playlist by gbroad84 on Spotify/1 - Dance With the Dead - Invader.mp3
Downloaded: Dance With the Dead - Invader
Downloading file to /home/azerty/tmp/deezloader/Synthwave_ a playlist by gbroad84 on Spotify/5 - Timecop1983 - Going Home.mp3
Downloaded: Timecop1983 - Going Home
Playlist finished: Synthwave, a playlist by gbroad84 on Spotify

`

**Comment by xyBuskin** [comment]
@ExtendLord Here we go (some of the files were already downloaded so i excluded all except the last msg):

Downloading file to /Users/adj/Music/Deezloader/Timecop1983 - Reflections/14 - Timecop1983 - After Life (Outro).mp3
Already downloaded: Timecop1983 - After Life (Outro)
Trace: TypeError: Cannot read property '1' of null
    at Deezer.<anonymous> (/Applications/DeezLoader.app/Contents/Resources/app/deezer-api.js:170:31)
    at Request.self.callback (/Applications/DeezLoader.app/Contents/Resources/app/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/Applications/DeezLoader.app/Contents/Resources/app/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/Applications/DeezLoader.app/Contents/Resources/app/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at process.<anonymous> (/Applications/DeezLoader.app/Contents/Resources/app/app.js:1126:13)
    at emitOne (events.js:101:20)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)

**Comment by canout** [comment]
I've read the code.
Problem solved in commit d6dc691.

**Comment by ExtendLord** [comment]
Now there should not be a crash.
The only bug in downloading content is "Unable to get track" which will not download a song because the song does not have a /track page.
I'm trying to figure out a solution.
