### ISSUE TITLE
App Crashes on Downloading Albums & Playlists URL

### ISSUE THREAD

**Issue by Razer2333** [ExtendLord/DeezLoader-Reborn#24]
copy a playlist link and start download but the app closed ater download 6 songs .. ive tested every playlist with every ip (vpn) .. ive changed download folder too but no luck

**Comment by syvhmx** [comment]
This issue is a duplicate from before:
`Deezloader Crashes on Downloading URL & Playlist`
Refer to that.

**Comment by Razer2333** [comment]
@syvhmx oh my bad sorry
but ive checked the fixed code and problem is still here
it still crashes whenever I attempt to download from a URL or Playlist

**Comment by syvhmx** [comment]
@Razer2333 Can you give the playlist link? I'll try downloading it.

**Comment by Razer2333** [comment]
@syvhmx This playlist for exampel :
http://www.deezer.com/en/playlist/2562102388

**Comment by ExtendLord** [comment]
@Razer2333 Can you please compile the project(Download the zip, extract and npm install && npm run dist on terminal/cmd) and then run deezloader in the terminal/cmd?

**Comment by Razer2333** [comment]
@ExtendLord Ive downloaded the dev version and i didnt get any cashes or force closes but
ive tried to download some playlists and there is toooo much Failed Downloads .. here is the errors :



Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Justi
n Bieber - Friends.mp3
Downloaded: Justin Bieber - Friends
error: error Error: Unable to get Track
    at Deezer.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-Reborn-ma
ster\dist\win-unpacked\resources\app\deezer-api.js:175:19)
    at Request.self.callback (C:\Users\Administrator\Downloads\DeezLoader-Reborn
-master\dist\win-unpacked\resources\app\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-Reborn-m
aster\dist\win-unpacked\resources\app\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-
Reborn-master\dist\win-unpacked\resources\app\node_modules\request\request.js:10
85:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Wafia
 - Only Love.mp3
Downloaded: Wafia - Only Love
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Smerz
 - Have fun.mp3
Downloaded: Smerz - Have fun
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\4 - Ed Sh
eeran - Shape of You.mp3
Downloaded: Ed Sheeran - Shape of You
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Miley
 Cyrus - Malibu.mp3
Downloaded: Miley Cyrus - Malibu
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - ZAYN
- Still Got Time.mp3
Downloaded: ZAYN - Still Got Time
error: error Error: Unable to get Track
    at Deezer.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-Reborn-ma
ster\dist\win-unpacked\resources\app\deezer-api.js:175:19)
    at Request.self.callback (C:\Users\Administrator\Downloads\DeezLoader-Reborn
-master\dist\win-unpacked\resources\app\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-Reborn-m
aster\dist\win-unpacked\resources\app\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-
Reborn-master\dist\win-unpacked\resources\app\node_modules\request\request.js:10
85:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Banks
 - Underdog.mp3
Downloaded: Banks - Underdog
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Rag'n
'Bone Man - Skin.mp3
Downloaded: Rag'n'Bone Man - Skin
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Calvi
n Harris - Rollin.mp3
Downloaded: Calvin Harris - Rollin
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Parce
ls - Overnight.mp3
Downloaded: Parcels - Overnight
error: error Error: Unable to get Track
    at Deezer.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-Reborn-ma
ster\dist\win-unpacked\resources\app\deezer-api.js:175:19)
    at Request.self.callback (C:\Users\Administrator\Downloads\DeezLoader-Reborn
-master\dist\win-unpacked\resources\app\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-Reborn-m
aster\dist\win-unpacked\resources\app\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-
Reborn-master\dist\win-unpacked\resources\app\node_modules\request\request.js:10
85:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Flawe
s - This Could Be Real.mp3
Downloaded: Flawes - This Could Be Real
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Sevda
liza - Hero.mp3
Downloaded: Sevdaliza - Hero
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Aluna
George - Your Drums_ Your Love.mp3
Downloaded: AlunaGeorge - Your Drums, Your Love
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\5 - Charl
ie Puth - We Don't Talk Anymore (feat. Selena Gomez).mp3
Downloaded: Charlie Puth - We Don't Talk Anymore (feat. Selena Gomez)
error: error Error: Unable to get Track
    at Deezer.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-Reborn-ma
ster\dist\win-unpacked\resources\app\deezer-api.js:175:19)
    at Request.self.callback (C:\Users\Administrator\Downloads\DeezLoader-Reborn
-master\dist\win-unpacked\resources\app\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-Reborn-m
aster\dist\win-unpacked\resources\app\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-
Reborn-master\dist\win-unpacked\resources\app\node_modules\request\request.js:10
85:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
error: error Error: Unable to get Track
    at Deezer.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-Reborn-ma
ster\dist\win-unpacked\resources\app\deezer-api.js:175:19)
    at Request.self.callback (C:\Users\Administrator\Downloads\DeezLoader-Reborn
-master\dist\win-unpacked\resources\app\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-Reborn-m
aster\dist\win-unpacked\resources\app\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-
Reborn-master\dist\win-unpacked\resources\app\node_modules\request\request.js:10
85:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Tep N
o - Me and My Guitar.mp3
Downloaded: Tep No - Me and My Guitar
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Leon
- Liar.mp3
Downloaded: Leon - Liar
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Jamie
 Woon - Skin.mp3
Downloaded: Jamie Woon - Skin
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Major
 Lazer - Cold Water (feat. Justin Bieber & MO) (Lost Frequencies Remix).mp3
Downloaded: Major Lazer - Cold Water (feat. Justin Bieber & MO) (Lost Frequencie
s Remix)
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\4 - Shura
 - Touch.mp3
Downloaded: Shura - Touch
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Chris
topher - Free Fall.mp3
Downloaded: Christopher - Free Fall
error: error Error: Unable to get Track
    at Deezer.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-Reborn-ma
ster\dist\win-unpacked\resources\app\deezer-api.js:175:19)
    at Request.self.callback (C:\Users\Administrator\Downloads\DeezLoader-Reborn
-master\dist\win-unpacked\resources\app\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-Reborn-m
aster\dist\win-unpacked\resources\app\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-
Reborn-master\dist\win-unpacked\resources\app\node_modules\request\request.js:10
85:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
error: error Error: Unable to get Track
    at Deezer.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-Reborn-ma
ster\dist\win-unpacked\resources\app\deezer-api.js:175:19)
    at Request.self.callback (C:\Users\Administrator\Downloads\DeezLoader-Reborn
-master\dist\win-unpacked\resources\app\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-Reborn-m
aster\dist\win-unpacked\resources\app\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-
Reborn-master\dist\win-unpacked\resources\app\node_modules\request\request.js:10
85:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\3 - SG Le
wis - Meant To Be.mp3
Downloaded: SG Lewis - Meant To Be
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\17 - Fake
ar - Song For Jo.mp3
Downloaded: Fakear - Song For Jo
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\15 - ZAYN
 - BLUE.mp3
Downloaded: ZAYN - BLUE
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\6 - James
 Vincent McMorrow - Get Low.mp3
Downloaded: James Vincent McMorrow - Get Low
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Bonob
o - Break Apart.mp3
Downloaded: Bonobo - Break Apart
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Milow
 - Howling At The Moon.mp3
Downloaded: Milow - Howling At The Moon
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\14 - Kygo
 - Carry Me.mp3
Downloaded: Kygo - Carry Me
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Snake
hips - Don't Leave.mp3
Downloaded: Snakehips - Don't Leave
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Honne
 - Warm On A Cold Night.mp3
Downloaded: Honne - Warm On A Cold Night
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Emily
 Jane White - Frozen Garden.mp3
Downloaded: Emily Jane White - Frozen Garden
error: error Error: Unable to get Track
    at Deezer.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-Reborn-ma
ster\dist\win-unpacked\resources\app\deezer-api.js:175:19)
    at Request.self.callback (C:\Users\Administrator\Downloads\DeezLoader-Reborn
-master\dist\win-unpacked\resources\app\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-Reborn-m
aster\dist\win-unpacked\resources\app\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (C:\Users\Administrator\Downloads\DeezLoader-
Reborn-master\dist\win-unpacked\resources\app\node_modules\request\request.js:10
85:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Ed Sh
eeran - Shape of You.mp3
Downloaded: Ed Sheeran - Shape of You
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\7 - Gavin
 James - 22.mp3
Downloaded: Gavin James - 22
Downloading file to C:\Users\Administrator\Downloads\Music\Easy Monday\1 - Gary
Clark Jr. - Take Me Down.mp3
Downloaded: Gary Clark Jr. - Take Me Down
Playlist finished: Easy Monday

**Comment by ExtendLord** [comment]
@Razer2333 I found out just now that the songs that has errors "Unable to get Track" are because of a 404 when trying to get to the page.
I'm trying to figure out a solution.

**Comment by Razer2333** [comment]
@ExtendLord i think its beacuse of ip adress & location .. dont know 🤔

**Comment by ExtendLord** [comment]
Fixed the issue dfb3460ae0a83dd6981ab3d73db5eec08bc2a6f1
 
But I need to just add the login window and 3.0.2 will be released.

**Comment by ExtendLord** [comment]
#14
