### ISSUE TITLE
Build issue - Windows

### ISSUE THREAD

**Issue by virtualviolet** [ExtendLord/DeezLoader-Reborn#40]
Hi Guys,

I have tried to build on MacOS and it fails, have now tried to build on Windows 7 and it also fails, please can you help me understand what is going on?

C:\Users\Kevin\Desktop\DeezLoader-Reborn-master>npm install

> electron@1.7.10 postinstall C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\n
de_modules\electron
> node install.js

> undefined postinstall C:\Users\Kevin\Desktop\DeezLoader-Reborn-master
> electron-builder install-app-deps

   electron-builder version=19.53.7
   loaded configuration file=package.json ("build" field)
   installing production dependencies platform=win32 arch=x64 appDir=C:\Users\K
vin\Desktop\DeezLoader-Reborn-master\app
npm notice created a lockfile as package-lock.json. You should commit this file

npm WARN DeezLoader-Reborn-master No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@1.2.0 (node_modu
es\7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin
linux@1.2.0: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":
x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_module
\7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin
mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"
64"})

added 315 packages in 139.265s

C:\Users\Kevin\Desktop\DeezLoader-Reborn-master>npm run dist

> @ dist C:\Users\Kevin\Desktop\DeezLoader-Reborn-master
> electron-builder

   electron-builder version=19.53.7
   loaded configuration file=package.json ("build" field)
   writing effective config file=dist\electron-builder.yaml
   rebuilding native production dependencies platform=win32 arch=x64
   asar using is disabled - it is strongly not recommended solution=enable asar
and use asarUnpack to unpack files that must be externally available
   packaging       platform=win32 arch=x64 electron=1.7.10 appOutDir=dist\win-u
packed
Downloading tmp-19536-0-electron-v1.7.10-win32-x64.zip
Downloading tmp-19536-0-electron-v1.7.10-win32-x64.zip
Downloading tmp-19536-0-electron-v1.7.10-win32-x64.zip
Downloading tmp-19536-1-SHASUMS256.txt-1.7.10
[============================================>] 100.0% of 2.96 kB (2.96 kB/s)
   downloading     path=C:\Users\Kevin\AppData\Local\electron-builder\cache\app
builder\app-builder-v0.5.0-x64 url=https://github.com/develar/app-builder/relea
es/download/v0.5.0/app-builder-v0.5.0-win-x64.7z
Error: Exit code: ENOENT. spawn C:\Users\Kevin\AppData\Local\electron-builder\c
che\app-builder\app-builder-v0.5.0-x64\app-builder.exe ENOENT
    at C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modules\builder-uti
\src\util.ts:122:16
    at exithandler (child_process.js:279:5)
    at ChildProcess.errorhandler (child_process.js:291:5)
    at ChildProcess.emit (events.js:160:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
From previous event:
    at exec (C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modules\build
r-util\src\util.ts:85:3)
    at C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modules\electron-bu
lder-lib\src\platformPackager.ts:596:23
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modul
s\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:149:20)
From previous event:
    at WinPackager.resolveIcon (C:\Users\Kevin\Desktop\DeezLoader-Reborn-master
node_modules\electron-builder-lib\out\platformPackager.js:635:11)
    at C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modules\electron-bu
lder-lib\src\platformPackager.ts:575:25
    at Generator.next (<anonymous>)
    at WinPackager.getOrConvertIcon (C:\Users\Kevin\Desktop\DeezLoader-Reborn-m
ster\node_modules\electron-builder-lib\out\platformPackager.js:610:11)
    at Lazy.WinPackager._iconPath.Lazy (C:\Users\Kevin\Desktop\DeezLoader-Rebor
-master\node_modules\electron-builder-lib\src\winPackager.ts:60:43)
    at Lazy.get value [as value] (C:\Users\Kevin\Desktop\DeezLoader-Reborn-mast
r\node_modules\lazy-val\src\main.ts:18:23)
    at WinPackager.getIconPath (C:\Users\Kevin\Desktop\DeezLoader-Reborn-master
node_modules\electron-builder-lib\src\winPackager.ts:200:27)
    at C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modules\electron-bu
lder-lib\src\winPackager.ts:297:33
    at Generator.next (<anonymous>)
    at WinPackager.signAndEditResources (C:\Users\Kevin\Desktop\DeezLoader-Rebo
n-master\node_modules\electron-builder-lib\out\winPackager.js:414:11)
    at C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modules\electron-bu
lder-lib\src\winPackager.ts:348:18
From previous event:
    at WinPackager.getOrConvertIcon (C:\Users\Kevin\Desktop\DeezLoader-Reborn-m
ster\node_modules\electron-builder-lib\out\platformPackager.js:610:11)
    at Lazy.WinPackager._iconPath.Lazy (C:\Users\Kevin\Desktop\DeezLoader-Rebor
-master\node_modules\electron-builder-lib\src\winPackager.ts:60:43)
    at Lazy.get value [as value] (C:\Users\Kevin\Desktop\DeezLoader-Reborn-mast
r\node_modules\lazy-val\src\main.ts:18:23)
    at WinPackager.getIconPath (C:\Users\Kevin\Desktop\DeezLoader-Reborn-master
node_modules\electron-builder-lib\src\winPackager.ts:200:27)
    at C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modules\electron-bu
lder-lib\src\winPackager.ts:297:33
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signAndEditResources (C:\Users\Kevin\Desktop\DeezLoader-Rebo
n-master\node_modules\electron-builder-lib\out\winPackager.js:414:11)
    at C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modules\electron-bu
lder-lib\src\winPackager.ts:348:18
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\nod
_modules\electron-builder-lib\out\winPackager.js:432:11)
    at C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modules\electron-bu
lder-lib\src\platformPackager.ts:216:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
From previous event:
    at WinPackager.doPack (C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node
modules\electron-builder-lib\out\platformPackager.js:283:11)
    at C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modules\electron-bu
lder-lib\src\platformPackager.ts:116:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_m
dules\electron-builder-lib\out\platformPackager.js:201:11)
    at C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modules\electron-bu
lder-lib\src\packager.ts:361:24
    at Generator.next (<anonymous>)
    at xfs.stat (C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modules\f
-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modules\graceful-fs
polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:167:5)
From previous event:
    at Packager.doBuild (C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_m
dules\electron-builder-lib\out\packager.js:423:11)
    at C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modules\electron-bu
lder-lib\src\packager.ts:305:52
    at Generator.next (<anonymous>)
    at C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modules\graceful-fs
graceful-fs.js:99:16
    at C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modules\graceful-fs
graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:149:20)
From previous event:
    at Packager._build (C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_mo
ules\electron-builder-lib\out\packager.js:367:11)
    at C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modules\electron-bu
lder-lib\src\packager.ts:267:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
From previous event:
    at Packager.build (C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_mod
les\electron-builder-lib\out\packager.js:323:11)
    at C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modules\electron-bu
lder\src\builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modules\ele
tron-builder\out\builder.js:61:21)
    at build (C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modules\elec
ron-builder\src\builder.ts:280:10)
    at then (C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_modules\elect
on-builder\src\cli\cli.ts:49:33)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
From previous event:
    at Object.args [as handler] (C:\Users\Kevin\Desktop\DeezLoader-Reborn-maste
\node_modules\electron-builder\src\cli\cli.ts:49:33)
    at Object.runCommand (C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node_
odules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\Users\Kevin\Desktop\DeezLoader-Rebo
n-master\node_modules\yargs\yargs.js:1041:24)
    at Object.get [as argv] (C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\no
e_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (C:\Users\Kevin\Desktop\DeezLoader-Reborn-master\node
modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3

**Comment by virtualviolet** [comment]
it appears to be a problem with electron-builder, but I have no information as to why app-builder.exe is exiting...
