### ISSUE TITLE
Deezloader - Mac - Crash

### ISSUE THREAD

**Issue by virtualviolet** [ExtendLord/DeezLoader-Reborn#42]
Hi

Whilst downloading Dezzloader crashed, the  output on the console was:

Unable to initialize Deezer API
Trace: TypeError: Cannot read property 'disk_number' of null
    at /Applications/DeezLoader.app/Contents/Resources/app/app.js:609:70
    at /Applications/DeezLoader.app/Contents/Resources/app/deezer-api.js:71:13
    at Request._callback (/Applications/DeezLoader.app/Contents/Resources/app/deezer-api.js:286:13)
    at self.callback (/Applications/DeezLoader.app/Contents/Resources/app/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Request.onRequestError (/Applications/DeezLoader.app/Contents/Resources/app/node_modules/request/request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at process.<anonymous> (/Applications/DeezLoader.app/Contents/Resources/app/app.js:1126:13)
    at emitOne (events.js:101:20)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)

**Comment by virtualviolet** [comment]
It has done this a few times now :-/ Upon restarting the app, the same album downloads fine. 

Please can you adjust how Deezloader handles exceptions like this and just delete the folder and restart the download... my js knowledge is poor otherwise I would fork and make the changes...

**Comment by ExtendLord** [comment]
Download 3.0.2 and try it to see if you will still have problems.

**Comment by virtualviolet** [comment]
Good man! I would have compiled it myself, but seem to have troubles with electron-builder :-(

Are they not just going to block the user account you have embedded? Wouldn't it make more sense to provide a login window and user user submitted details?

**Comment by ExtendLord** [comment]
@virtualviolet There is a login page now, you need a deezer account(Does not matter if its free or not)

**Comment by virtualviolet** [comment]
Oh cool... Can you update the mac version? it is still 3.01..

**Comment by virtualviolet** [comment]
Ok, I'm closing this as the stability/error handling seems to be better
