### ISSUE TITLE
crash cancelling the first item in the download list

### ISSUE THREAD

**Issue by virtualviolet** [ExtendLord/DeezLoader-Reborn#46]
If I cancel the first item in the download list with other items waiting, the app crashes, v3.0.1 did this also.

**Console output:**

Trace: Error: Callback was already called.
    at C:\Program Files\DeezLoader\resources\app\node_modules\async\dist\async.js:955:32
    at C:\Program Files\DeezLoader\resources\app\app.js:249:25
    at C:\Program Files\DeezLoader\resources\app\app.js:682:29
    at Request.<anonymous> (C:\Program Files\DeezLoader\resources\app\deezer-api.js:285:3)
    at emitNone (events.js:86:13)
    at Request.emit (events.js:188:7)
    at Request.abort (C:\Program Files\DeezLoader\resources\app\node_modules\request\request.js:1177:8)
    at Deezer.cancelDecryptTrack (C:\Program Files\DeezLoader\resources\app\deezer-api.js:291:18)
    at Socket.<anonymous> (C:\Program Files\DeezLoader\resources\app\app.js:527:36)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at process.<anonymous> (C:\Program Files\DeezLoader\resources\app\app.js:1138:13)
    at emitOne (events.js:101:20)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)

**Comment by ExtendLord** [comment]
#45 Duplicate
