### ISSUE TITLE
Crashes when I try to download

### ISSUE THREAD

**Issue by D0ragn** [ExtendLord/DeezLoader-Reborn#51]
I updated as you recomended for the folder with the [...] points endedn but now i'm unable to download any album, it keeps crashing, even I tried to download an album I downloaded whit the 3.0.1 version but keeping crashing

**Comment by ExtendLord** [comment]
Run deezloader using cmd

**Comment by D0ragn** [comment]
C:\Program Files\DeezLoader>
Server is running @ localhost:1730
Trace: TypeError: Cannot read property '0' of undefined
    at Deezer.<anonymous> (C:\Program Files\DeezLoader\resources\app\deezer-api.js:189:47)
    at Request.self.callback (C:\Program Files\DeezLoader\resources\app\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (C:\Program Files\DeezLoader\resources\app\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (C:\Program Files\DeezLoader\resources\app\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at process.<anonymous> (C:\Program Files\DeezLoader\resources\app\app.js:1138:13)
    at emitOne (events.js:101:20)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)

**Comment by ExtendLord** [comment]
@D0ragn Fixed https://github.com/ExtendLord/DeezLoader-Reborn/commit/626bdfec97f9e34dae74147f3ac2a5199181548c
Compile and try again.
Your account details were incorrect and the software did not detected it, now it should(Fixed it).

**Comment by D0ragn** [comment]
When I use my pasword to login it fails I tried 4 times then I logged into but then the app crashes, I think the login function is not full working

**Comment by ExtendLord** [comment]
@D0ragn Can you run deezloader using cmd?
Did you cloned the repo and compiled and used that version?
Did you used email and not username?
What was the error that was shown?
Did you checked auto login?
