### ISSUE TITLE
Syncing problem between tagging and image grabbing.

### ISSUE THREAD

**Issue by JoelAlone** [ExtendLord/DeezLoader-Reborn#7]
Each time downloading the same album different songs have them missing.

**Comment by ExtendLord** [comment]
Names of the albums that have missing metadata please

**Comment by JoelAlone** [comment]
Basically every album if effected songs just randomly don't have metadata, probably it'd also happend when downloading single songs. Here is an example of downloading Metallica album 3 times:
![0of1f7l](https://user-images.githubusercontent.com/20167275/34915531-bbca0460-f928-11e7-8824-5aafac7730f3.png)
![ucbkyak](https://user-images.githubusercontent.com/20167275/34915532-bbe47c78-f928-11e7-8346-6552428f2a3e.png)
![wrhljrl](https://user-images.githubusercontent.com/20167275/34915533-bbffd770-f928-11e7-95f5-dc5dfe46fd9a.png)
Each time different songs have missing metadata

**Comment by ExtendLord** [comment]
@JoelAlone I'm releasing an update very soon(1-3 Hours) about the tags problem.
The update will also remove the flaclib folder because I have found a node js flac wrapper so its multi platform now.

**Comment by JoelAlone** [comment]
Nice thank you

**Comment by JoelAlone** [comment]
@ExtendLord Can you upload updated exes? I compiled from source and now app is constantly crashing after downloading couple songs

**Comment by ExtendLord** [comment]
@JoelAlone I'm compiling for windows mac and linux and patching something

Can you run deezloader using cmd?

It will show you some logs from the software

When it will crash send me the logs of the crash from the cmd

**Comment by JoelAlone** [comment]
@ExtendLord 
```Server is running @ localhost:1730
Attempting connection to API
Attempting connection to API
{ title: 'Intro/ 50 Cent / The Massacre',
  artist: '50 Cent',
  album: 'The Massacre',
  performerInfo: '50 Cent',
  trackNumber: '1/22',
  partOfSet: '1/1',
  label: 'Universal Music Polska Sp. z o.o.',
  ISRC: 'USIR10500302',
  duration: '41',
  explicit: '1',
  genre: 'Rap/Hip Hop',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/8550ab66b25e9ccfbe3cad3cdb7d8284/1200x1200.jpg',
  year: '2005' }
Downloading file to D:\Music\50 Cent\The Massacre\Intro_ 50 Cent _ The Massacre.flac
Downloaded: 50 Cent - Intro/ 50 Cent / The Massacre
{ title: 'In My Hood',
  artist: '50 Cent',
  album: 'The Massacre',
  performerInfo: '50 Cent',
  trackNumber: '2/22',
  partOfSet: '1/1',
  label: 'Universal Music Polska Sp. z o.o.',
  ISRC: 'USIR10500303',
  duration: '231',
  explicit: '1',
  genre: 'Rap/Hip Hop',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/8550ab66b25e9ccfbe3cad3cdb7d8284/1200x1200.jpg',
  year: '2005' }
Downloading file to D:\Music\50 Cent\The Massacre\In My Hood.flac
Downloaded: 50 Cent - In My Hood
Trace: { Error: ENOENT: no such file or directory, open 'C:\Users\Joel\AppData\Local\Programs\DeezLoader\https:\e-cdns-images.dzcdn.net\images\cover\8550ab66b25e9ccfbe3cad3cdb7d8284\1200x1200.jpg'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at C:\Users\Joel\AppData\Local\Programs\DeezLoader\resources\app\app.js:753:48
    at C:\Users\Joel\AppData\Local\Programs\DeezLoader\resources\app\node_modules\graceful-fs\graceful-fs.js:99:16
    at C:\Users\Joel\AppData\Local\Programs\DeezLoader\resources\app\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:114:15)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\Joel\\AppData\\Local\\Programs\\DeezLoader\\https:\\e-cdns-images.dzcdn.net\\images\\cover\\8550ab66b25e9ccfbe3cad3cdb7d8284\\1200x1200.jpg' }
    at process.<anonymous> (C:\Users\Joel\AppData\Local\Programs\DeezLoader\resources\app\app.js:1123:13)
    at emitOne (events.js:101:20)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)
```

**Comment by ExtendLord** [comment]
@JoelAlone Can you give me the link to the album/playlist that you've tried to download?

**Comment by JoelAlone** [comment]
@ExtendLord http://www.deezer.com/en/album/5941967

**Comment by ExtendLord** [comment]
@JoelAlone DeezLoader Reborn is updated, clone again and compile or download the installer and try again.

**Comment by JoelAlone** [comment]
@ExtendLord Still crashes
```C:\Program Files\DeezLoader>
Server is running @ localhost:1730
Attempting connection to API
{ title: 'Earth',
  artist: 'Jesper Kyd',
  album: 'Assassin\'s Creed 2 (Original Game Soundtrack)',
  performerInfo: 'Jesper Kyd',
  trackNumber: '1/35',
  partOfSet: '1/2',
  label: 'Ubisoft Music',
  ISRC: 'CA2BN0900076',
  duration: '238',
  explicit: '0',
  genre: 'Pop',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/557de281363393f045699c536413c406/1200x1200.jpg',
  year: '2009' }
Downloading file to D:\Music\Jesper Kyd\Assassin's Creed 2 (Original Game Soundtrack)\Earth.flac
Downloaded: Jesper Kyd - Earth
{ title: 'Venice Rooftops',
  artist: 'Jesper Kyd',
  album: 'Assassin\'s Creed 2 (Original Game Soundtrack)',
  performerInfo: 'Jesper Kyd',
  trackNumber: '2/35',
  partOfSet: '1/2',
  label: 'Ubisoft Music',
  ISRC: 'CA2BN0900077',
  duration: '198',
  explicit: '0',
  genre: 'Pop',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/557de281363393f045699c536413c406/1200x1200.jpg',
  year: '2009' }
Downloading file to D:\Music\Jesper Kyd\Assassin's Creed 2 (Original Game Soundtrack)\Venice Rooftops.flac
Downloaded: Jesper Kyd - Venice Rooftops
{ title: 'Ezio\'s Family',
  artist: 'Jesper Kyd',
  album: 'Assassin\'s Creed 2 (Original Game Soundtrack)',
  performerInfo: 'Jesper Kyd',
  trackNumber: '3/35',
  partOfSet: '1/2',
  label: 'Ubisoft Music',
  ISRC: 'CA2BN0900078',
  duration: '237',
  explicit: '0',
  genre: 'Pop',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/557de281363393f045699c536413c406/1200x1200.jpg',
  year: '2009' }
Downloading file to D:\Music\Jesper Kyd\Assassin's Creed 2 (Original Game Soundtrack)\Ezio's Family.flac
Downloaded: Jesper Kyd - Ezio's Family
{ title: 'Florence Tarantella',
  artist: 'Jesper Kyd',
  album: 'Assassin\'s Creed 2 (Original Game Soundtrack)',
  performerInfo: 'Jesper Kyd',
  trackNumber: '4/35',
  partOfSet: '1/2',
  label: 'Ubisoft Music',
  ISRC: 'CA2BN0900079',
  duration: '111',
  explicit: '0',
  genre: 'Pop',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/557de281363393f045699c536413c406/1200x1200.jpg',
  year: '2009' }
Downloading file to D:\Music\Jesper Kyd\Assassin's Creed 2 (Original Game Soundtrack)\Florence Tarantella.flac
Downloaded: Jesper Kyd - Florence Tarantella
{ title: 'Home In Florence',
  artist: 'Jesper Kyd',
  album: 'Assassin\'s Creed 2 (Original Game Soundtrack)',
  performerInfo: 'Jesper Kyd',
  trackNumber: '5/35',
  partOfSet: '1/2',
  label: 'Ubisoft Music',
  ISRC: 'CA2BN0900080',
  duration: '270',
  explicit: '0',
  genre: 'Pop',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/557de281363393f045699c536413c406/1200x1200.jpg',
  year: '2009' }
Downloading file to D:\Music\Jesper Kyd\Assassin's Creed 2 (Original Game Soundtrack)\Home In Florence.flac
Downloaded: Jesper Kyd - Home In Florence
{ title: 'Approaching Target 1',
  artist: 'Jesper Kyd',
  album: 'Assassin\'s Creed 2 (Original Game Soundtrack)',
  performerInfo: 'Jesper Kyd',
  trackNumber: '6/35',
  partOfSet: '1/2',
  label: 'Ubisoft Music',
  ISRC: 'CA2BN0900081',
  duration: '215',
  explicit: '0',
  genre: 'Pop',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/557de281363393f045699c536413c406/1200x1200.jpg',
  year: '2009' }
Downloading file to D:\Music\Jesper Kyd\Assassin's Creed 2 (Original Game Soundtrack)\Approaching Target 1.flac
Downloaded: Jesper Kyd - Approaching Target 1
{ title: 'Approaching Target 2',
  artist: 'Jesper Kyd',
  album: 'Assassin\'s Creed 2 (Original Game Soundtrack)',
  performerInfo: 'Jesper Kyd',
  trackNumber: '7/35',
  partOfSet: '1/2',
  label: 'Ubisoft Music',
  ISRC: 'CA2BN0900082',
  duration: '367',
  explicit: '0',
  genre: 'Pop',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/557de281363393f045699c536413c406/1200x1200.jpg',
  year: '2009' }
Downloading file to D:\Music\Jesper Kyd\Assassin's Creed 2 (Original Game Soundtrack)\Approaching Target 2.flac
Downloaded: Jesper Kyd - Approaching Target 2
{ title: 'Venice Fight',
  artist: 'Jesper Kyd',
  album: 'Assassin\'s Creed 2 (Original Game Soundtrack)',
  performerInfo: 'Jesper Kyd',
  trackNumber: '8/35',
  partOfSet: '1/2',
  label: 'Ubisoft Music',
  ISRC: 'CA2BN0900083',
  duration: '121',
  explicit: '0',
  genre: 'Pop',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/557de281363393f045699c536413c406/1200x1200.jpg',
  year: '2009' }
Downloading file to D:\Music\Jesper Kyd\Assassin's Creed 2 (Original Game Soundtrack)\Venice Fight.flac
Downloaded: Jesper Kyd - Venice Fight
{ title: 'Florence Escape',
  artist: 'Jesper Kyd',
  album: 'Assassin\'s Creed 2 (Original Game Soundtrack)',
  performerInfo: 'Jesper Kyd',
  trackNumber: '9/35',
  partOfSet: '1/2',
  label: 'Ubisoft Music',
  ISRC: 'CA2BN0900084',
  duration: '170',
  explicit: '0',
  genre: 'Pop',
  image: 'https://e-cdns-images.dzcdn.net/images/cover/557de281363393f045699c536413c406/1200x1200.jpg',
  year: '2009' }
Downloading file to D:\Music\Jesper Kyd\Assassin's Creed 2 (Original Game Soundtrack)\Florence Escape.flac
Downloaded: Jesper Kyd - Florence Escape
Trace: { Error: ENOENT: no such file or directory, open 'C:\Program Files\DeezLoader\https:\e-cdns-images.dzcdn.net\images\cover\557de281363393f045699c536413c406\1200x1200.jpg'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at C:\Program Files\DeezLoader\resources\app\app.js:756:48
    at C:\Program Files\DeezLoader\resources\app\node_modules\graceful-fs\graceful-fs.js:99:16
    at C:\Program Files\DeezLoader\resources\app\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:114:15)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Program Files\\DeezLoader\\https:\\e-cdns-images.dzcdn.net\\images\\cover\\557de281363393f045699c536413c406\\1200x1200.jpg' }
    at process.<anonymous> (C:\Program Files\DeezLoader\resources\app\app.js:1126:13)
    at emitOne (events.js:101:20)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)
```

**Comment by ExtendLord** [comment]
@JoelAlone Can you please replace the app/app.js with this https://pastebin.com/LDeChz8D and compile again?
This one contains a different debug codes.
Not sure why does let cover = fs.readFileSync(metadata.image); tries to open Program Files + the image.

**Comment by JoelAlone** [comment]
@ExtendLord btw where does it store config files, maybe I should clear them after update? Uninstalling desn't remove them

**Comment by ExtendLord** [comment]
@JoelAlone Clean %temp% folder and %appdata%/Deezloader

**Comment by JoelAlone** [comment]
```C:\Users\Joel\AppData\Local\Programs\DeezLoader>
Server is running @ localhost:1730
Attempting connection to API
Downloading file to D:\Music\Jesper Kyd\Assassin's Creed 2 (Original Game Soundtrack)\Earth.flac
Downloaded: Jesper Kyd - Earth
[ 'TITLE=Earth',
  'ALBUM=Assassin\'s Creed 2 (Original Game Soundtrack)',
  'GENRE=Pop',
  'PERFORMER=Jesper Kyd',
  'ALBUMARTIST=Jesper Kyd',
  'ARTIST=Jesper Kyd',
  'TRACKNUMBER=1/35',
  'DISCNUMBER=1/2',
  'PUBLISHER=Ubisoft Music',
  'LENGTH=238',
  'ISRC=CA2BN0900076',
  'ITUNESADVISORY=0',
  'DATE=2009' ]
IMAGE=C:/Users/Joel/AppData/Local/Temp/deezloader-imgs/Earth.jpg
Downloading file to D:\Music\Jesper Kyd\Assassin's Creed 2 (Original Game Soundtrack)\Venice Rooftops.flac
Downloaded: Jesper Kyd - Venice Rooftops
[ 'TITLE=Venice Rooftops',
  'ALBUM=Assassin\'s Creed 2 (Original Game Soundtrack)',
  'GENRE=Pop',
  'PERFORMER=Jesper Kyd',
  'ALBUMARTIST=Jesper Kyd',
  'ARTIST=Jesper Kyd',
  'TRACKNUMBER=2/35',
  'DISCNUMBER=1/2',
  'PUBLISHER=Ubisoft Music',
  'LENGTH=198',
  'ISRC=CA2BN0900077',
  'ITUNESADVISORY=0',
  'DATE=2009' ]
IMAGE=https://e-cdns-images.dzcdn.net/images/cover/557de281363393f045699c536413c406/1200x1200.jpg
Trace: { Error: ENOENT: no such file or directory, open 'C:\Users\Joel\AppData\Local\Programs\DeezLoader\https:\e-cdns-images.dzcdn.net\images\cover\557de281363393f045699c536413c406\1200x1200.jpg'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at C:\Users\Joel\AppData\Local\Programs\DeezLoader\resources\app\app.js:756:48
    at C:\Users\Joel\AppData\Local\Programs\DeezLoader\resources\app\node_modules\graceful-fs\graceful-fs.js:99:16
    at C:\Users\Joel\AppData\Local\Programs\DeezLoader\resources\app\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:114:15)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\Joel\\AppData\\Local\\Programs\\DeezLoader\\https:\\e-cdns-images.dzcdn.net\\images\\cover\\557de281363393f045699c536413c406\\1200x1200.jpg' }
    at process.<anonymous> (C:\Users\Joel\AppData\Local\Programs\DeezLoader\resources\app\app.js:1128:13)
    at emitOne (events.js:101:20)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)


```

**Comment by JoelAlone** [comment]
Good thing is that all songs i've downloaded so far had their metadata

**Comment by ExtendLord** [comment]
@JoelAlone The problem is that the image grabber is not syncing with the tagger 😠
And all of that because of JavaScript, the worst programming language.

**Comment by ExtendLord** [comment]
Can you try to clone the source, compile and try again?

**Comment by JoelAlone** [comment]
Ok I'll try in a moment

**Comment by JoelAlone** [comment]
@ExtendLord https://pastebin.com/7kKLnviW

**Comment by JoelAlone** [comment]
Same error

**Comment by ExtendLord** [comment]
https://github.com/ExtendLord/DeezLoader-Reborn/commit/514191f73fd73a33841109a91c4a1684d4993a59
Sorry for that huge delay, fixed the problem, if you still have the issue, don't hesitate to comment here or open a new issue if its a different issue.
