### ISSUE TITLE
v3.0.3 PC - Crash at login

### ISSUE THREAD

**Issue by virtualviolet** [ExtendLord/DeezLoader-Reborn#77]
Hi this new version now crashes at login.

**With auto login enabled the console output is:**

Trace: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Program Files\DeezLoader\resources\app\deezer-api.js:312:29)
    at Request.self.callback (C:\Program Files\DeezLoader\resources\app\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (C:\Program Files\DeezLoader\resources\app\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (C:\Program Files\DeezLoader\resources\app\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at process.<anonymous> (C:\Program Files\DeezLoader\resources\app\app.js:1212:13)
    at emitOne (events.js:101:20)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)

**Without auto login enabled the console output is:**
Trace: SyntaxError: Unexpected token p in JSON at position 130603
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Program Files\DeezLoader\resources\app\deezer-api.js:312:29)
    at Request.self.callback (C:\Program Files\DeezLoader\resources\app\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (C:\Program Files\DeezLoader\resources\app\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (C:\Program Files\DeezLoader\resources\app\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at process.<anonymous> (C:\Program Files\DeezLoader\resources\app\app.js:1212:13)
    at emitOne (events.js:101:20)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)

The PC version 3.0.2 was also unstable.

**Comment by ExtendLord** [comment]
@virtualviolet Hi
Please clone the repository and replace deezer-api.js with this https://pastebin.com/tJuDgWzp .
Try again and send me the logs.

**Comment by virtualviolet** [comment]
The Mac version also crashes :-/

Console:
Unable to initialize Deezer API
Trace: TypeError: Cannot read property 'data' of null
    at /Applications/DeezLoader.app/Contents/Resources/app/app.js:498:28
    at /Applications/DeezLoader.app/Contents/Resources/app/deezer-api.js:182:13
    at Request._callback (/Applications/DeezLoader.app/Contents/Resources/app/deezer-api.js:310:13)
    at self.callback (/Applications/DeezLoader.app/Contents/Resources/app/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Request.onRequestError (/Applications/DeezLoader.app/Contents/Resources/app/node_modules/request/request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at process.<anonymous> (/Applications/DeezLoader.app/Contents/Resources/app/app.js:1212:13)
    at emitOne (events.js:101:20)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)

**Comment by virtualviolet** [comment]
when you say clone, are you asking me to build or just replace a file in the deezloader303 app within the folder it is installed in?

**Comment by virtualviolet** [comment]
what version of node are you using to build? I installed version 9.4

**Comment by ExtendLord** [comment]
It could be an internet issue,
The software probably tries to connect to the internet before the login.

**Comment by ExtendLord** [comment]
https://github.com/ExtendLord/DeezLoader-Reborn/commit/49c8b0ecb189f656bb6cdd2884db52abc9de27a1
Fixed, download the repo again and compile.

**Comment by virtualviolet** [comment]
little snitch doesn't flag anything...

I'm compiling, you didn't answer my question though. What version of node are you using or recommend?

**Comment by ExtendLord** [comment]
I said before 9.4.0

**Comment by virtualviolet** [comment]
Ok, managed to build ok and launches ok... nice work

**Comment by virtualviolet** [comment]
It's not your app, I have just gone back to the older version 3.0.2 and it is unable to access the API

**Comment by virtualviolet** [comment]
@ExtendLord 

Just so you know ;-)
Github has very simple rights/privileges (and even simpler management for them).

If you are not a collaborator of a repo, then (in regards to issues)

you can open issues
you can comment on all existing issues (open or closed)
you can close your own issues
you can re-open your own issues *if you closed them yourself
you cannot close or re-open issues opened by someone else
you cannot re-open your own issues if a repo collaborator closed them

**Comment by ExtendLord** [comment]
@virtualviolet Thanks for the info.
If you need me to open it, next time don't just open a new one, tell me to reopen or say that you are still facing issues.

**Comment by virtualviolet** [comment]
ok no probs, I really appreciate what your doing btw. sometimes it doesn't
across the right way using text...
