### ISSUE TITLE
V3.0.3 - Crashes at launch

### ISSUE THREAD

**Issue by virtualviolet** [ExtendLord/DeezLoader-Reborn#80]
This is not fixed, don't why you closed it before I had even responded...

It launched ok, but after I searched for an artist it popped up a message saying contact the developer.

**The console output was:** 
Unable to initialize Deezer API

Now it refuses to launch properly, tries to auto login and then bombs out.

**Console output:**
Trace: TypeError: Cannot read property 'data' of null
    at /Applications/DeezLoader.app/Contents/Resources/app/app.js:498:28
    at /Applications/DeezLoader.app/Contents/Resources/app/deezer-api.js:192:13
    at Request._callback (/Applications/DeezLoader.app/Contents/Resources/app/deezer-api.js:320:13)
    at self.callback (/Applications/DeezLoader.app/Contents/Resources/app/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Request.onRequestError (/Applications/DeezLoader.app/Contents/Resources/app/node_modules/request/request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at process.<anonymous> (/Applications/DeezLoader.app/Contents/Resources/app/app.js:1216:13)
    at emitOne (events.js:101:20)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)

**Comment by NicolasPL64** [comment]
how do you open the app with console? (cmd)

**Comment by ExtendLord** [comment]
Then open the other issue, why did you created a new one?

**Comment by virtualviolet** [comment]
I can't, there is no option to re open and even replying doesn't re open.

**Comment by virtualviolet** [comment]
@NicolasPL64 open a command prompt and then launch the app from the command line, it should dump info and errors to standard output.
