### ISSUE TITLE
Cannot read property 'disk_number' of null

### ISSUE THREAD

**Issue by virtualviolet** [ExtendLord/DeezLoader-Reborn#84]
V303 has crashed a few times with the following error:

Unable to initialize Deezer API
Trace: TypeError: Cannot read property 'disk_number' of null
    at /Users/kevin/Desktop/DeezLoader303.app/Contents/Resources/app/app.js:677:70
    at /Users/kevin/Desktop/DeezLoader303.app/Contents/Resources/app/deezer-api.js:92:13
    at Request._callback (/Users/kevin/Desktop/DeezLoader303.app/Contents/Resources/app/deezer-api.js:310:13)
    at self.callback (/Users/kevin/Desktop/DeezLoader303.app/Contents/Resources/app/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Request.onRequestError (/Users/kevin/Desktop/DeezLoader303.app/Contents/Resources/app/node_modules/request/request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at process.<anonymous> (/Users/kevin/Desktop/DeezLoader303.app/Contents/Resources/app/app.js:1212:13)
    at emitOne (events.js:101:20)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)

**Comment by ExtendLord** [comment]
What is the name of the track/album/playlist that you have tried to download?

**Comment by virtualviolet** [comment]
Hybrid - Wider Angle (Special Edition)

It's fine now, downloaded ok. But Deezer have limited the traffic to my IP
address. from 3MB/sec down to 14KB/sec. Done a lot of testing this
afternoon and confirmed this to be correct, but I have a work around for
now....
